name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    # Checkout the repository's code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install dependencies using npm
    - name: Install dependencies
      run: npm install

    # Build the project
    - name: Build project
      run: npm run build
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Set your environment variables here
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        VITE_BOT_USERNAME: ${{ secrets.VITE_BOT_USERNAME }}

    # Deploy to GitHub Pages using the peaceiris action
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to push changes
        publish_dir: ./dist  # Directory to deploy from (make sure it's correct)
